default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: 3306

development:
  <<: *default
  database: canyons_development

test:
  <<: *default
  database: canyons_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
